.github/workflows/build.yml
A step can't have both "uses" and "run" so the cosign step needed to be split.
=> fix(ci): split cosign steps

.github/workflows/build.yml, Containerfile, README.md
Also makes the source image's tag easier to understand in the Containerfile.
=> refactor: use repo name as default image name

build.sh
Fedora 40 broke the example for editing systemd configuration behavior. Decided to use a simpler example.
=> fix: use a working example

build.sh
I think it's a bit confusing to have `RUN` as part of the command, which looks more like a containerfile command than a shell command.
=> style: Remove RUN from commented command

.github/workflows/build.yml
That should get rid of the warnings during builds: "Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, docker/metadata-action@v4."
=> chore: update Node 16 actions to latest versions

.github/workflows/build.yml
* `--disable-content-trust` is not needed according to [buildah docs](https://github.com/containers/buildah/blob/main/docs/buildah-build.1.md).
* Enable `zstd` compression: Fedora 39 is EOL, our new friends will only use Fedora 40 or newer, beside the custom layer, it can also reduce the download size if upstream isn't using `zstd` like Bluefin. 
*  Bump sigstore/cosign-installer to 3.7.0
=> feat(ci): buildah: del `disable-content-trust`, enable zstd compression; bump sigstore/cosign-installer to 3.7.0

.github/workflows/build.yml
This makes it so that inprogress builds are cancelled when you make a new push. Matches the rest of ublue.
=> feat(ci): add concurrency

.github/workflows/build.yml
I believe these should be enabled by default, since they make builds a lot slower, but it is nice having some docs about it
=> chore: add rechunk and maximize-build-storage examples on the build workflow

.github/workflows/build.yml
This ended up getting removed after that PR adding the achillobator workflows. This should allow the users to use passwords and stuff to push the images to GHCR or other registries like docker.io and quay
=> feat: (re)add registry login to push to GHCR

.github/workflows/build.yml
Added a lower casing of the image name should it be uppercased. Switched variables to use lowercased image name.
I noticed that during the signing of the container image, it would fail with an error
parsing reference: could not parse reference
After adding a step to lowercase the image name as well, it was able to pass.
=> Signing need lowercase image name

Containerfile
This requires Composefs to be used, which we are not yet in a position to enable.
We need to wait until either bootc container lint allows us to exclude checks, or when the atomic desktops switch over to composefs.
=> fix: remove bootc container lint check

build.sh
Some repos, such as Bazzite, change `dnf` to a no-op so end users don't try it and encounter an error when booted. 
Inside the Containerfile, we should default to `dnf5` until the wrapper is updated to detect when running in CI.
Fixes the issue seen in the SCaLE demo.
=> fix: install packages via dnf5

.github/workflows/build-iso.yml, README.md, iso.toml
This PR adds a new optional workflow to the image template that allows a user to create an ISO using the `bootc-image-builder` utility. It supports either `amd64` and `arm64` architectures however not both in the same workflow due to limitations around the `choice` input for actions.
After some discussion in the discord about the best way to accomplish this feature we decided it was best to just start with what Bluefin is doing and upload to S3 rather than try to always come in under the 2GB limit that Actions has. In my testing a barebones ISO comes in at 1.9GB, so adding a couple things can easily push this over the limit. In order to try to make the DX/UX as smooth as possible I decided to 1) make the workflow compatible with any S3 provider rather than just R2 and 2) keep all the S3 …
=> feat(build-iso): Add ability to generate ISO

.gitignore, Justfile
This is a collection of minor fixes based on things I encountered when trying out this template repo:
- Correctly use `$target_image` instead of `$image_name` in a few places in the justfile
- Make whitespace consistent in justfile
- Add the `output` folder to .gitignore to avoid accidentally checking in a bunch of junk when testing things out locally
=> fix: Justfile variable usage and formatting

.github/renovate.json5
Even if they say that its best for people that want the best practices on the docs, we should make people using this template have this safer thing by default
https://docs.renovatebot.com/presets-config/#configbest-practices
=> ci: make sure renovate uses best-practices preset

.github/renovate.json5, Containerfile
This one makes it so we (and people that use this template) dont need to manually bump the docker images all the time, like we ran into with [bluefin LTS](https://github.com/ublue-os/bluefin-lts/pull/398#issuecomment-2726873005)
=> ci: use the same renovate config as bluefin-lts

.gitignore, Justfile
Before it would delete your outputs before starting the build. That means miss-typing the command for example could lead to losing data. This also creates separate folders for each type to avoid collision.
=> feat: build in tempdir and move files on success

Containerfile
This is now fixed in Bazzite, Bluefin, Aurora, and Main.
=> feat: Enable linting by default

Justfile
Due to the lack of a `--rootfs` build argument in the Justfile by default, building virtual machines keeps failing because of the aforementioned issue, so I decided to open up a PR to add this argument to avoid future headaches for future custom image builders.
I have used Btrfs as the default option due to it being the default filesystem choice on Fedora and the Universal Blue images.
=> fix: Add rootfs argument to _build-bib

Justfile
This PR fixes weird behavior with the `just run-vm` command that causes the output to print out in a regular shell outside the command, making operation via the terminal difficult in certain situations, and removes an unnecessary `fg` command due to the lack of job-control capability.
It also (in my experience) helps fix an issue about Intel GPU drivers taking an unusually long time to install in the QEMU Docker image.
=> fix: fix weird behavior in just run-vm

Justfile
introduced in 083532b8ff
```
error: Recipe line has inconsistent leading whitespace. Recipe started with `␠␠␠␠␠` but found line with `␠␠␠␠` ——▶ Justfile:341:1
│
341 │     set -eoux pipefail
│ ^^^^
```
=> fix(just): fix syntax error

Containerfile
ostree container commit is not needed anymore when using bootc container lint.
=> Containerfile: ostree container commit is not needed

.github/workflows/build.yml
Random failures of this action may occur when many runners are started at the same time and github can't allocate enough disk space.
- adds a fallback to the old action if that is the case.
- logic has been used in production in Aurora and Bluefin since 2 months
See: https://github.com/ublue-os/container-storage-action/pull/11
=> feat(ci): add fallback condition for btrfs bind mount
